export default [
  { id: 'introduction', title: 'Introduction',  level: 1 },
  { id: 'what-is-zepton', title: 'What is Zepton?', level: 2 },
  { id: 'quick-start', title: 'Quick Start', level: 2 },
  { id: 'essentials', title: 'Essentials', level: 1 },
  { id: 'the-application-instance', title: 'The application instance', level: 2 },
  { id: 'a-simple-component', title: 'A simple component', level: 2 },
  { id: 'adding-state', title: 'Adding state', level: 2 },
  { id: 'reactivity', title: 'Reactivity', level: 2 },
  { id: 'attributes', title: 'Attributes', level: 2 },
  { id: 'class-helpers', title: 'Class helpers', level: 2 },
  { id: 'style-helpers', title: 'Style helpers', level: 2 },
  { id: 'inserting-html', title: 'Inserting HTML', level: 2 },
  { id: 'conditional-rendering', title: 'Conditional rendering', level: 2 },
  { id: 'list-rendering', title: 'List rendering', level: 2 },
  { id: 'event-handling', title: 'Event handling', level: 2 },
  { id: 'lifecycle-events', title: 'Lifecycle events', level: 2 },
  { id: 'components', title: 'Components', level: 1 },
  { id: 'passing-props', title: 'Passing props', level: 2 },
  { id: 'component-events', title: 'Component events', level: 2 },
  { id: 'slots', title: 'Slots', level: 2 },
  { id: 'dynamic-components', title: 'Dynamic components', level: 2 },
  { id: 'transitions', title: 'Transitions', level: 1 },
  { id: 'passing-properties-to-the-transition-function', title: 'Passing properties to the transition function', level: 2 },
  { id: 'custom-transition-function', title: 'Custom transition function', level: 2 },
  { id: 'providing-different-transitions-for-enter-and-exit', title: 'Providing different transitions for enter and exit', level: 2 },
  { id: 'the-list-of-transitions-provided-by-zepton', title: 'The list of transitions provided by zepton', level: 2 },
]
